### ISSUE TITLE
hubot deploy:version triggers an exception

### ISSUE THREAD

**Issue by meltwater-haven** [atmos/hubot-deploy#121]
I'm hitting an exception while setting up hubot deploy

@atmos any help would be appreciated

```
2017-02-08T13:26:27.764918+00:00 app[web.1]: [Wed Feb 08 2017 13:26:27 GMT+0000 (UTC)] DEBUG Message 'hubot deploy:version' matched regex //^\s*[@]?hubot[:,]?\s*(?:deploy\:version$)/i/
2017-02-08T13:26:27.772163+00:00 app[web.1]: [Wed Feb 08 2017 13:26:27 GMT+0000 (UTC)] ERROR TypeError: object is not a function
2017-02-08T13:26:27.772166+00:00 app[web.1]:   at TextListener.Listener.call (/app/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
2017-02-08T13:26:27.772166+00:00 app[web.1]:   at Robot.receive (/app/node_modules/hubot/src/robot.coffee:197:9, <js>:143:33)
2017-02-08T13:26:27.772167+00:00 app[web.1]:   at HipChat.Adapter.receive (/app/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
2017-02-08T13:26:27.772168+00:00 app[web.1]:   at /app/node_modules/hubot-hipchat/src/hipchat.coffee:190:11, <js>:237:26
2017-02-08T13:26:27.772169+00:00 app[web.1]:   at invokeCallback (/app/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:161:15)
2017-02-08T13:26:27.772169+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:193:9)
2017-02-08T13:26:27.772170+00:00 app[web.1]:   at /app/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:13:16
2017-02-08T13:26:27.772171+00:00 app[web.1]:   at process._tickCallback (node.js:355:11)
```

Thanks

**Comment by salimane** [comment]
a nice "how to" describing how to setup hubot + hubot-deploy + hipchat + github Auto-Deployment  + heaven + capistrano . I'm now having problems setting up the whole and understanding how they all connect to each other.
Thanks

cc @atmos

**Comment by atmos** [comment]
I've stopped using hubot for chat automation in favor of slack slash commands and oauth. 

Debugging this stuff across chat networks and deployment strategies has proven to be a huge pain in the butt.  I'm only targeting heroku and slack right now with https://github.com/atmos/slash-heroku

**Comment by salimane** [comment]
@atmos could you recommend another library/app that can do hipchat + hubot + capistrano ?
Thanks

**Comment by atmos** [comment]
I really don't. If you need that then I'd probably stick with atmos/heaven and hubot-deploy version 0.13.27.

Since I'm really only working with heroku pipelines lately I don't know how well these things even work together anymore.

**Comment by salimane** [comment]
@atmos thanks for the reply. I was thinking of trying/customising https://github.com/atmos/slash-heroku to work with a capistrano strategy, would you be open to that ?
Thanks

**Comment by atmos** [comment]
slash-heroku won't work with hipchat.

**Comment by salimane** [comment]
@atmos yep this is fine, I would be using slack :)
