### ISSUE TITLE
Can't get tests to run successfully

### ISSUE THREAD

**Issue by andycox** [atmos/hubot-deploy#50]
Since the build is currently green, I know this is more user error than a problem with hubot-deploy, but I'm hoping someone can lead a Node/Mocha newbie in the right direction.

So, when I do a clean checkout of the repo (OS X Yosemite with node 0.12 installed via Homebrew) and try to run the tests, here's what happens:
```
$  hubot-deploy git:(master) node -v
v0.12.7
$  hubot-deploy git:(master) npm -v
2.12.1
$  hubot-deploy git:(master) npm install
npm WARN package.json hubot-deploy@0.6.53 No license field.
npm WARN prefer global coffee-script@1.9.3 should be installed with -g
timeago@0.1.0 node_modules/timeago

sprintf@0.1.3 node_modules/sprintf

hubot-test-helper@0.0.2 node_modules/hubot-test-helper

inflection@1.3.6 node_modules/inflection

chai@1.0.4 node_modules/chai

coffee-script@1.9.3 node_modules/coffee-script

mocha@2.2.5 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.1
├── growl@1.8.1
├── commander@2.3.0
├── diff@1.4.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

octonode@0.5.0 node_modules/octonode
├── deep-extend@0.4.0
├── randomstring@1.0.7
└── request@2.27.0 (forever-agent@0.5.2, aws-sign@0.3.0, qs@0.6.6, tunnel-agent@0.3.0, oauth-sign@0.3.0, cookie-jar@0.3.0, json-stringify-safe@5.0.1, mime@1.2.11, node-uuid@1.4.3, form-data@0.1.4, http-signature@0.10.1, hawk@1.0.0)

hubot@2.15.0 node_modules/hubot
├── optparse@1.0.4
├── cline@0.8.2
├── log@1.4.0
├── scoped-http-client@0.11.0
├── async@0.9.2
├── chalk@1.1.0 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── coffee-script@1.6.3
├── connect-multiparty@1.2.5 (qs@2.2.5, on-finished@2.1.1, multiparty@3.3.2, type-is@1.5.7)
└── express@3.18.1 (basic-auth@1.0.0, utils-merge@1.0.0, merge-descriptors@0.0.2, cookie@0.1.2, fresh@0.2.4, escape-html@1.0.1, range-parser@1.0.2, vary@1.0.1, cookie-signature@1.0.5, media-typer@0.3.0, parseurl@1.3.0, methods@1.1.0, content-disposition@0.5.0, depd@1.0.1, debug@2.1.3, commander@1.3.2, etag@1.5.1, proxy-addr@1.0.8, send@0.10.1, mkdirp@0.5.0, connect@2.27.1)
$  hubot-deploy git:(master) npm test

> hubot-deploy@0.6.53 test /Users/acox/Projects/3rd-party/hubot-deploy
> cake test

/Users/acox/Projects/3rd-party/hubot-deploy/Cakefile:11
        throw err;
              ^
Error: Command failed: /bin/sh -c NODE_ENV=test ./node_modules/.bin/mocha

  at ChildProcess.exithandler (child_process.js:751:12)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1015:16)
  at Socket.<anonymous> (child_process.js:1183:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:485:12)

npm ERR! Test failed.  See above for more details.
$  hubot-deploy git:(master) NODE_ENV=test ./node_modules/.bin/mocha


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  37 passing (80ms)
  1 pending
  3 failing

  1) The Hubot Script displays the version:
     expected [ 'hubot', 'hubot-deploy v0.6.53/hubot v2.15.0/node v0.12.7' ] to deeply equal undefined
    at Context.<anonymous> (test/index_test.coffee:18:12)


  2) The Hubot Script displays deployment environment help:
     TypeError: Cannot read property '1' of undefined
    at Context.<anonymous> (test/index_test.coffee:23:31)


  3) The Hubot Script does not allow deploying in random room if allowed_rooms is configured:
     TypeError: Cannot read property '1' of undefined
    at Context.<anonymous> (test/index_test.coffee:47:31)
```
Any thoughts? I suspect there's something whack with my environment, but I don't know where to begin.

**Comment by andycox** [comment]
I backed Hubot down to 2.13.2 to match what's in the [latest Travis build](https://travis-ci.org/atmos/hubot-deploy/builds/72881468), et voila!

```
hubot-deploy git:(test-fix) npm list hubot
hubot-deploy@0.6.53 /Users/acox/Projects/3rd-party/hubot-deploy
└── hubot@2.13.2

➜  hubot-deploy git:(test-fix) npm test

> hubot-deploy@0.6.53 test /Users/acox/Projects/3rd-party/hubot-deploy
> cake test



  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  40 passing (47ms)
  1 pending
```

There were some [pretty significant differences between 2.13.2 and 2.14.0](https://github.com/github/hubot/compare/v2.13.2...v2.14.0), so it looks like that's the main candidate. I'm happy to dig in to see if I can figure out what's going on, but for now I'll submit a PR to lock Hubot at 2.13.2 or below.

**Comment by atmos** [comment]
Thanks!
