### ISSUE TITLE
ERROR TypeError: Cannot read property 'forUser' of undefined

### ISSUE THREAD

**Issue by mcapanema** [atmos/hubot-deploy#71]
Hello,

I am trying to configure hubot-deploy but I am getting the following error:
```
hubot> hubot deploy-token:verify:github
hubot> [Tue Nov 03 2015 19:38:26 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'forUser' of undefined
  at TextListener.callback (/home/hubot/hubot/node_modules/hubot-deploy/src/scripts/token.coffee:47:13, <js>:47:26)
  at executeListener (/home/hubot/hubot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/home/hubot/hubot/node_modules/hubot/src/middleware.coffee:41:37, <js>:32:16)
  at /home/hubot/hubot/node_modules/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/home/hubot/hubot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/home/hubot/hubot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
  at /home/hubot/hubot/node_modules/hubot/src/middleware.coffee:46:7, <js>:35:22
  at process._tickCallback (node.js:355:11)
hubot>
```

I have tried to reset the github token and insert a new one but it didn't work, although it says the token is valid:
```
hubot> hubot deploy-token:reset:github
hubot> [Tue Nov 03 2015 19:42:20 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'forUser' of undefined
  at TextListener.callback (/home/hubot/hubot/node_modules/hubot-deploy/src/scripts/token.coffee:38:5, <js>:39:18)
  at executeListener (/home/hubot/hubot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/home/hubot/hubot/node_modules/hubot/src/middleware.coffee:41:37, <js>:32:16)
  at /home/hubot/hubot/node_modules/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/home/hubot/hubot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/home/hubot/hubot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
  at /home/hubot/hubot/node_modules/hubot/src/middleware.coffee:46:7, <js>:35:22
  at process._tickCallback (node.js:355:11)
hubot>
hubot> hubot deploy-token:set:github <my_token>
hubot> Shell: Your GitHub token is valid. I stored it for future use.
[Tue Nov 03 2015 19:43:18 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'forUser' of undefined
  at /home/hubot/hubot/node_modules/hubot-deploy/src/scripts/token.coffee:32:9, <js>:30:29
  at /home/hubot/hubot/node_modules/hubot-deploy/src/models/token_verifier.coffee:18:11, <js>:25:20
  at Client.errorHandle (/home/hubot/hubot/node_modules/hubot-deploy/node_modules/octonode/lib/octonode/client.js:196:14)
  at Request._callback (/home/hubot/hubot/node_modules/hubot-deploy/node_modules/octonode/lib/octonode/client.js:210:24)
  at Request.self.callback (/home/hubot/hubot/node_modules/hubot-deploy/node_modules/octonode/node_modules/request/request.js:373:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/home/hubot/hubot/node_modules/hubot-deploy/node_modules/octonode/node_modules/request/request.js:1318:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/home/hubot/hubot/node_modules/hubot-deploy/node_modules/octonode/node_modules/request/request.js:1266:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
hubot>
```

My hubot-deploy is the following:
```
hubot> hubot deploy:version
hubot> hubot-deploy v0.10.1/hubot v2.16.0/node v0.12.7
```

Do you guys have any idea what is happening ?

**Comment by atmos** [comment]
I've been migrating this to support hipchat as well as slack. In the past I'd only been running this on slack but I need to go through and confirm that this is something that's working successfully across multiple chat networks. I should have a fix for this in the next day or so. Or at least a meaningful error message for this situation. You can probably get by with version 0.6.53 in the meantime.

**Comment by mcapanema** [comment]
Thank you for the help @atmos it works now:
```
hubot> hubot deploy:version
hubot> hubot-deploy v0.6.53/hubot v2.16.0/node v0.12.7
```

```
hubot> hubot deploy-token:reset
hubot> Shell: I nuked your deployment token. I'll use my default token until you configure another.

hubot> hubot deploy-token:set <my_tokem>
hubot> Shell: Your token is valid. I stored it for future use.
```
